algo = input('Digite algo: ')
print("Tipo primitivo de '{}' é:".format(algo), type(algo))
print('alpha:      ', algo.isalpha())
print('alnum:      ', algo.isalnum())
print('numeric:    ', algo.isnumeric())
print('ascii:      ', algo.isascii())
print('digit:      ', algo.isdigit())
print('decimal:    ', algo.isdecimal())
print('identifier: ', algo.isidentifier())
print('space:      ', algo.isspace())
print('slower:     ', algo.islower())
print('title:      ', algo.istitle())
print('upper:      ', algo.isupper())
